(1, 'Khác', 'Other', NULL),
(2, 'Công viên', 'Park', NULL),
(3, 'Nhà hàng', 'Restaurant', NULL),
(4, 'Khách sạn', 'Hotel', NULL),
(5, 'Bãi biển', 'Beach', NULL),
(6, 'Trung tâm mua sắm', 'Shopping Mall', NULL),
(7, 'Bảo tàng', 'Museum', NULL),
(8, 'Khu vui chơi', 'Amusement Park', NULL),
(9, 'Quán cà phê', 'Cafe', NULL),
(10, 'Di tích lịch sử', 'Historical Site', NULL),
(11, 'Chợ địa phương', 'Local Market', NULL),
(12, 'Hồ nước', 'Lake', NULL),
(13, 'Làng văn hóa', 'Cultural Village', NULL),
(14, 'Du thuyền', 'Cruise', NULL),
(15, 'Khu sinh thái', 'Ecological Area', NULL),
(16, 'Chùa', 'Temple', NULL),
(17, 'Cầu', 'Bridge', NULL),
(18, 'Đền', 'Shrine', NULL),
(19, 'Động', 'Cave', NULL),
(20, 'Đèo', 'Mountain Pass', NULL),
(21, 'Đầm', 'Lagoon', NULL),
(22, 'Đảo', 'Island', NULL),
(23, 'Thác', 'Waterfall', NULL),
(24, 'Hải đăng', 'Lighthouse', NULL),
(25, 'Núi', 'Mountain', NULL),
(26, 'Nhà thờ', 'Church', NULL);
(27, 'Phố cổ', 'Old Quarter', NULL),
(28, 'Rừng', 'Forest', NULL),
(29, 'Suối', 'Stream/Spring', NULL);