INSERT INTO comments (user_id, post_id, content) VALUES
(23, 1, 'Hồ Gươm đẹp quá!'),
(14, 1, 'Phở Thìn ngon lắm!'),
(37, 2, 'Đà Lạt lãng mạn!'),
(9, 2, 'Chợ đêm đông không?'),
(28, 3, 'Hội An lung linh!'),
(42, 3, 'Cao lầu siêu ngon!'),
(5, 4, 'Phú Quốc như tranh!'),
(31, 4, 'Hải sản giá thế nào?'),
(17, 5, 'Sapa lạnh lắm hả?'),
(46, 5, 'Fansipan đáng đi!'),
(12, 6, 'Huế thơ mộng ghê!'),
(33, 6, 'Ca Huế hay không?'),
(25, 7, 'Hạ Long kỳ vĩ!'),
(4, 7, 'Du thuyền đắt không?'),
(39, 8, 'Côn Đảo hoang sơ!'),
(11, 8, 'Bãi Đầm Trầu đẹp!'),
(20, 9, 'Nha Trang vui lắm!'),
(48, 9, 'Vinpearl Land thế nào?'),
(7, 10, 'Mũi Né cát đẹp!'),
(29, 10, 'Suối Tiên thú vị!'),
(15, 11, 'Tam Đảo mát mẻ!'),
(36, 11, 'Nhà thờ đá đẹp!'),
(8, 12, 'Đà Nẵng hiện đại!'),
(44, 12, 'Cầu Rồng ấn tượng!'),
(27, 13, 'Cát Bà yên bình!'),
(3, 13, 'Kayak vui không?'),
(50, 14, 'Lý Sơn đẹp quá!'),
(19, 14, 'San hô đẹp không?'),
(41, 15, 'Phong Nha hùng vĩ!'),
(10, 15, 'Zipline có đáng thử?'),
(22, 16, 'Mai Châu thư giãn!'),
(35, 16, 'Bản Lác thế nào?'),
(47, 17, 'Vũng Tàu gần gũi!'),
(13, 17, 'Hải sản ngon lắm!'),
(26, 18, 'Quy Nhơn thơ mộng!'),
(38, 18, 'Eo Gió đẹp không?'),
(16, 19, 'Hà Giang tuyệt vời!'),
(2, 19, 'Đèo Mã Pí Lèng đẹp!'),
(34, 20, 'Hồ Cốc hoang sơ!'),
(21, 20, 'Bánh xèo ngon không?'),
(43, 21, 'Bến Tre sông nước!'),
(5, 21, 'Kẹo dừa thơm lắm!'),
(30, 22, 'Cần Thơ nhộn nhịp!'),
(49, 22, 'Chợ nổi vui không?'),
(11, 23, 'Đồng Hới yên bình!'),
(24, 23, 'Biển Nhật Lệ đẹp!'),
(17, 24, 'An Giang độc đáo!'),
(6, 24, 'Rừng tràm thế nào?'),
(40, 25, 'Mộc Châu xanh mát!'),
(32, 25, 'Hoa cải đẹp quá!'),
(9, 26, 'Hồ Ba Bể đẹp!'),
(46, 26, 'Động Puông thú vị!'),
(23, 27, 'Tràng An như tranh!'),
(48, 27, 'Thịt dê ngon không?'),
(37, 28, 'Cà Mau đặc biệt!'),
(42, 28, 'Rừng U Minh đẹp!'),
(15, 29, 'Lào Cai khám phá!'),
(28, 29, 'Chợ Bắc Hà vui!'),
(7, 30, 'Buôn Ma Thuột chill!'),
(31, 30, 'Thác Dray Nur đẹp!'),
(20, 31, 'Pleiku gió ngàn!'),
(12, 31, 'Biển Hồ đẹp không?'),
(33, 32, 'Hải Phòng sôi động!'),
(25, 32, 'Bánh đa cua ngon!'),
(4, 33, 'Núi Bà Đen hùng vĩ!'),
(39, 33, 'Bánh tráng ngon lắm!'),
(11, 34, 'Bạc Liêu độc đáo!'),
(20, 34, 'Cánh đồng gió đẹp!'),
(48, 35, 'Sóc Trăng văn hóa!'),
(7, 35, 'Chùa Dơi lạ quá!'),
(29, 36, 'Kiên Giang biển đẹp!'),
(15, 36, 'Bún kèn ngon không?'),
(36, 37, 'Thác Bản Ba đẹp!'),
(44, 37, 'Chợ phiên thú vị!'),
(27, 38, 'Mù Cang Chải đẹp!'),
(3, 38, 'Ruộng bậc thang đẹp!'),
(50, 39, 'Lạng Sơn biên giới!'),
(19, 39, 'Vịt quay ngon lắm!'),
(41, 40, 'Cô Tô hoang sơ!'),
(10, 40, 'Mực nướng ngon không?'),
(22, 41, 'Quy Nhơn võ đài!'),
(35, 41, 'Tháp Chăm cổ kính!'),
(47, 42, 'Kon Tum độc đáo!'),
(13, 42, 'Nhà rông đẹp không?'),
(26, 43, 'Gia Lai hùng vĩ!'),
(38, 43, 'Phở khô ngon lắm!'),
(16, 44, 'Phú Quý biển đẹp!'),
(2, 44, 'Cá mú nướng ngon!'),
(34, 45, 'Tân Lập rừng đẹp!'),
(21, 45, 'Lẩu mắm ngon không?'),
(43, 46, 'Đồng Tháp sen hồng!'),
(5, 46, 'Bánh xèo ngon lắm!'),
(30, 47, 'Trà Vinh yên bình!'),
(49, 47, 'Bánh pía thơm ngon!'),
(11, 48, 'Vĩnh Long sông nước!'),
(24, 48, 'Chợ nổi nhộn nhịp!'),
(17, 49, 'Hậu Giang xanh mát!'),
(6, 49, 'Cá thòi lòi ngon!'),
(40, 50, 'Tiền Giang trái ngọt!'),
(32, 50, 'Hủ tiếu Mỹ Tho ngon!');


INSERT INTO comments (user_id, post_id, content) VALUES
(1,1,'Hồ Gươm sáng sớm rất yên bình! \nĐi bộ quanh hồ, ghé ăn phở Thìn, ngon tuyệt. Nhớ thử cà phê trứng nhé!'),(2,1,'Phở Thìn ngon lắm!'),(3,1,'Chợ Đồng Xuân đông không?'),(4,1,'Cà phê trứng tuyệt!'),(5,1,'Hà Nội đi mùa thu đẹp nhất! \nVăn Miếu cổ kính, chụp ảnh rất chill. Đừng bỏ qua bún chả!'),
(6,2,'Đà Lạt lãng mạn! \nChợ đêm nhộn nhịp, bánh tráng nướng ngon. Hồ Xuân Hương buổi tối rất thơ mộng.'),(7,2,'Chợ đêm vui lắm!'),(8,2,'Hồ Xuân Hương đẹp!'),(9,2,'Thác Datanla thú vị! \nMáng trượt siêu vui, nhưng nhớ mặc áo mưa để tránh ướt!'),(10,2,'Bánh tráng nướng ngon!'),
(11,2,'Đà Lạt lạnh không?'),(12,2,'Sữa đậu nành nóng ngon! \nChợ đêm đông vui, nhiều món ăn vặt hấp dẫn.'),(13,2,'Thác Datanla giá vé?'),(14,2,'Đà Lạt hoa đẹp! \nThung Lũng Tình Yêu có nhiều góc chụp ảnh, rất đáng ghé!'),
(15,3,'Hội An lung linh! \nĐèn lồng buổi tối đẹp mê hồn, đi thuyền sông Hoài rất thơ.'),(16,3,'Cao lầu siêu ngon!'),(17,3,'Đèn lồng đẹp quá!'),(18,3,'Sông Hoài thơ mộng! \nChè bắp Hội An ngọt thanh, ăn là ghiền.'),(19,3,'Hội An đêm đẹp!'),
(20,4,'Phú Quốc biển đẹp! \nLặn san hô ở Hòn Thơm tuyệt vời, nước trong vắt.'),(21,4,'Hải sản tươi ngon!'),(22,4,'Sunset Sanato đẹp lắm! \nChụp ảnh hoàng hôn ở đây đẹp như tranh, nhớ đi sớm.'),(23,4,'Lặn san hô thích!'),(24,4,'Chợ đêm đông không?'),
(25,5,'Sapa lạnh thật! \nBản Cát Cát rất đáng ghé, văn hóa dân tộc thú vị.'),(26,5,'Fansipan đáng đi!'),(27,5,'Bản Cát Cát đẹp!'),
(28,6,'Huế mộng mơ lắm! \nĐại Nội cổ kính, nghe ca Huế trên sông Hương rất chill.'),(29,6,'Bún bò ngon tuyệt!'),(30,6,'Ca Huế nghe chill!'),(31,6,'Huế lăng tẩm đẹp!'),
(32,7,'Hạ Long kỳ vĩ! \nDu thuyền 1 ngày, ngắm hang Sửng Sốt, rất đáng trải nghiệm.'),(33,7,'Hang Sửng Sốt đẹp!'),(34,7,'Du thuyền giá thế nào?'),(35,7,'Kayaking vui lắm! \nVịnh Hạ Long nước xanh, chèo kayak rất thư giãn.'),(36,7,'Hải sản trên thuyền!'),
(37,9,'Nha Trang biển xanh! \nLặn biển Hòn Mun thấy nhiều cá, nước trong veo.'),(38,9,'Vinpearl Land vui không?'),(39,9,'Hòn Mun san hô đẹp!'),(40,9,'Nha Trang lặn vui!'),
(41,10,'Mũi Né cát vàng! \nĐồi cát bay chụp ảnh đẹp, trượt cát rất vui.'),(42,10,'Suối Tiên thú vị!'),(43,10,'Tôm hùm giá thế nào?'),
(44,12,'Đà Nẵng hiện đại! \nCầu Rồng phun lửa tối thứ bảy, rất đáng xem.'),(45,12,'Mì Quảng ngon lắm!'),(46,12,'Bà Nà Hills đẹp! \nCáp treo dài, cảnh như châu Âu, nhớ mang áo ấm.'),(47,12,'Biển Mỹ Khê đẹp!'),
(48,14,'Lý Sơn đảo ngọc! \nĐảo Bé nước trong, lặn san hô rất thích.'),(49,14,'Tỏi Lý Sơn ngon!'),(50,14,'Đỉnh Thới Lới đẹp! \nNgắm toàn cảnh đảo, hoàng hôn rất đẹp.'),(1,14,'Lý Sơn nước trong!'),
(2,15,'Phong Nha hùng vĩ! \nĐi thuyền sông Son, động Thiên Đường đẹp mê hồn.'),(3,15,'Zipline vui lắm!'),(4,15,'Sông Son đẹp quá!'),(5,15,'Hang động đẹp!'),
(6,17,'Vũng Tàu gần gũi! \nHải sản bãi Sau tươi ngon, giá hợp lý.'),(7,17,'Hải sản bãi Sau ngon!'),(8,17,'Hồ Đá Xanh đẹp!'),
(9,18,'Quy Nhơn thơ mộng! \nKỳ Co nước hai màu, chụp ảnh rất đẹp.'),(10,18,'Eo Gió gió mát!'),(11,18,'Cua huỳnh đế ngon!'),
(12,19,'Hà Giang cảnh đẹp! \nĐèo Mã Pí Lèng hùng vĩ, đi xe máy rất đáng.'),(13,19,'Sông Nho Quế đẹp!'),(14,19,'Hà Giang xe máy!'),
(15,21,'Bến Tre sông nước! \nChèo thuyền trên sông, nghe đờn ca tài tử.'),(16,21,'Kẹo dừa mua đâu?'),(17,21,'Đờn ca tài tử hay!'),
(18,22,'Cần Thơ chợ nổi! \nSáng sớm đi thuyền, ăn bún nước lèo ngon.'),(19,22,'Bún nước lèo ngon!'),(20,22,'Chợ nổi sáng sớm!'),
(21,25,'Mộc Châu hoa cải! \nĐồi chè trái tim chụp ảnh đẹp, rất xanh.'),(22,25,'Sữa tươi ngon lắm!'),(23,25,'Thác Dải Yếm đẹp!'),
(24,27,'Tràng An như tranh! \nĐi thuyền ngắm hang động, rất thư giãn.'),(25,27,'Thịt dê núi ngon!'),(26,27,'Chùa Bái Đính đẹp!'),
(27,29,'Lào Cai chợ phiên! \nChợ Bắc Hà nhộn nhịp, thử thắng cố.'),(28,29,'Thắng cố ngon không?'),(29,29,'Chợ Bắc Hà vui!'),
(30,32,'Hải Phòng bánh đa! \nBánh đa cua đậm đà, ăn là ghiền.'),(31,32,'Đồ Sơn biển đẹp!'),(32,32,'Hải Phòng sôi động!'),
(33,1,'Hà Nội đi bộ vui!'),(34,1,'Phở Thìn đông không?'),(35,1,'Hồ Gươm buổi tối! \nChợ đêm cuối tuần đông vui, nhiều đồ ăn.'),(36,1,'Chợ Đồng Xuân rẻ!'),
(37,2,'Đà Lạt hoàng hôn! \nHồ Xuan Hương lúc chiều tà đẹp, rất chill.'),(38,2,'Chợ đêm đông vui!'),(39,2,'Bánh tráng nướng đâu?'),(40,2,'Đà Lạt đi mấy ngày?'),
(41,3,'Hội An chè bắp! \nĐi bộ phố cổ, đèn lồng lung linh.'),(42,3,'Sông Hoài buổi tối!'),(43,3,'Cao lầu giá bao nhiêu?'),
(44,4,'Phú Quốc lặn san hô! \nHòn Thơm nước trong, hải sản tươi.'),(45,4,'Sunset Sanato chụp ảnh!'),(46,4,'Hải sản Hàm Ninh! \nChợ đêm Phú Quốc nhiều món ngon, giá ổn.'),(47,4,'Chợ đêm Phú Quốc!'),
(48,5,'Sapa cáp treo đẹp! \nĐỉnh Fansipan mây bồng bềnh, rất đáng đi.'),(49,5,'Bản Cát Cát vui!'),(50,5,'Rượu táo mèo ngon!'),
(1,6,'Huế lăng Khải Định! \nKiến trúc độc đáo, bún bò ngon.'),(2,6,'Sông Hương thơ mộng!'),(3,6,'Bún bò giá rẻ!'),
(4,7,'Hạ Long hang động! \nKayaking ở vịnh rất thú vị, nước xanh.'),(5,7,'Du thuyền bao lâu?'),(6,7,'Hải sản trên thuyền!'),
(7,9,'Nha Trang lặn biển! \nVinpearl Land vui, phù hợp cả gia đình.'),(8,9,'Hòn Mun nước trong!'),(9,9,'Tháp Bà Ponagar đẹp!'),
(10,10,'Mũi Né trượt cát! \nĐồi cát bay bình minh đẹp, jeep vui.'),(11,10,'Suối Tiên nước mát!'),(12,10,'Mũi Né bình minh!'),
(13,12,'Đà Nẵng cầu Rồng! \nBiển Mỹ Khê sạch, sóng nhẹ, rất chill.'),(14,12,'Cầu Rồng buổi tối!'),(15,12,'Mì Quảng giá rẻ!'),
(16,14,'Lý Sơn san hô! \nĐảo Bé lặn biển, nước trong veo.'),(17,14,'Tỏi Lý Sơn thơm!'),(18,14,'Đảo Bé nước trong!'),
(19,15,'Phong Nha sông Son! \nĐộng Thiên Đường rộng, đẹp như tranh.'),(20,15,'Hang động đẹp quá!'),(21,15,'Zipline động Thiên Đường!'),
(22,17,'Vũng Tàu tượng Chúa! \nHồ Đá Xanh chụp ảnh đẹp, rất chill.'),(23,17,'Biển đông vui!'),
(24,18,'Quy Nhơn Kỳ Co! \nNước biển hai màu, chụp ảnh đẹp.'),(25,18,'Eo Gió chụp ảnh!'),
(26,19,'Hà Giang đèo đẹp! \nSông Nho Quế xanh, đi thuyền rất chill.'),(27,19,'Đèo Mã Pí Lèng!'),
(28,21,'Bến Tre chèo thuyền! \nVườn dừa xanh, kẹo dừa thơm ngon.'),(29,21,'Đờn ca tài tử hay!'),
(30,22,'Cần Thơ sáng sớm! \nChợ nổi Cái Răng nhộn nhịp, bún ngon.'),(31,22,'Chợ nổi Cái Răng!'),
(32,25,'Mộc Châu hoa đẹp! \nThác Dải Yếm nước mát, rất thư giãn.'),(33,25,'Đồi chè đẹp quá!'),
(34,27,'Tràng An thuyền đẹp! \nHang động mát, phong cảnh như tranh.'),(35,27,'Cơm cháy ngon không?'),
(36,29,'Lào Cai văn hóa! \nChợ phiên Bắc Hà nhiều món ăn lạ.'),(37,29,'Chợ Bắc Hà đông!'),
(38,32,'Hải Phòng biển đẹp! \nBánh đa cua đậm đà, rất đáng thử.'),(39,32,'Bánh đa cua ngon!'),
(40,1,'Hà Nội phở ngon! \nChợ Đồng Xuân nhiều đồ lưu niệm rẻ.'),(41,1,'Chợ đêm cuối tuần vui!'),
(42,2,'Đà Lạt không khí mát! \nChợ đêm nhiều món ăn vặt ngon.'),(43,2,'Hồ Xuân Hương chill!'),
(44,3,'Hội An thuyền đẹp! \nPhố cổ buổi tối lung linh, rất chill.'),(45,3,'Đèn lồng chụp ảnh!'),
(46,4,'Phú Quốc cát trắng! \nHải sản chợ đêm tươi, giá hợp lý.'),(47,4,'Hòn Thơm có gì?'),
(48,5,'Sapa văn hóa đẹp! \nThịt nướng và rượu táo mèo ngon.'),(49,5,'Cáp treo Fansipan đẹp!'),
(50,6,'Huế nghe ca Huế! \nSông Hương buổi tối rất thơ mộng.'),(1,6,'Lăng Khải Định đẹp!'),
(2,7,'Hạ Long kayak thích! \nNước xanh, hang động đẹp, rất đáng đi.'),(3,7,'Hang Sửng Sốt rộng!'),
(4,9,'Nha Trang vui lắm! \nLặn biển Hòn Mun nhiều cá, nước trong.'),(5,9,'Vinpearl Land giá vé?'),
(6,10,'Mũi Né hải sản! \nTôm hùm nướng ngon, giá hơi cao.'),(7,10,'Đồi cát bay đẹp!'),
(8,12,'Đà Nẵng biển đẹp! \nMỹ Khê sạch, mì Quảng rất ngon.'),(9,12,'Bà Nà cáp treo!'),
(10,14,'Lý Sơn cảnh đẹp! \nTỏi Lý Sơn thơm, mua làm quà.'),(11,14,'Đỉnh Thới Lới chill!'),
(12,15,'Phong Nha zipline vui! \nSông Son thơ mộng, hang động đẹp.'),(13,15,'Động Thiên Đường mê!'),
(14,17,'Hải sản bãi Sau!'),(15,18,'Eo Gió gió mát!'),
(16,19,'Sông Nho Quế chill!'),(17,21,'Kẹo dừa thơm ngon!'),
(18,22,'Bún nước lèo ngon!'),(19,25,'Mộc Châu thác đẹp!'),
(20,27,'Tràng An cảnh đẹp!'),(21,29,'Chợ Bắc Hà vui!'),
(22,32,'Hải Phòng sôi động!');